# config/_default/languages.fr.toml

title = "InVR - InTech Paris"                                               # * ... [OK]

[author]
name = ""                                                                   # * ... ToDo
image = ""                                                                  # * ... ToDo
headline = "In'VR c'est pas n'importe quoi"                                 # * ... ToDo
bio = "Ça fout l'feu, fait fondre, ça t'handicape quand tu l'as pas"        # * ... ToDo
links = [
  { twitter = "https://twitter.com/intechinfo" }
]                                                                           # * ... ToDo
