# config/_default/languages.en.toml

title = "InVR - Intech Paris"                                               # * ... [OK]

[author]
name = "InVR"
image = "img/in-vr-logo-welcome-page.png"
headline = "Infinitely creative solutions"
bio = "Collective entirely dedicated to the world of Virtual Reality, InVR offers you the best information and experiences that the Metaverse has to offer"
links = [
  { twitter = "https://twitter.com/InVR_Paris" },
  { github = "https://github.com/InVR-Intech-Paris" }
]                                                                           # * ... ToDo
