# config/_default/languages.en.toml

title = "InVR - InTech Paris"                                               # * ... [OK]

[author]
name = ""                                                                   # * ... ToDo
image = ""                                                                  # * ... ToDo
headline = "Infinitely creative solutions"
bio = "Collective entirely dedicated to the world of Virtual Reality, InVR offers you the best information and experiences that the Metaverse has to offer"
links = [
  { twitter = "https://twitter.com/InVR_Paris" }
]                                                                           # * ... ToDo
