# config/_default/menus.fr.toml

[[main]]
  name = "Rejoignez le staff !"
  pre = "join-us"
  url = "https://docs.google.com/forms/d/e/1FAIpQLSclmWkxxPw0YzV88jpH0Ro0KMTrTV66EtN43z_jNrXmnULeCw/viewform"
  weight = 5

[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Topics"
  pageRef = "topics"
  weight = 20

[[main]]
  identifier = "twitter"
  pre = "twitter"
  url = "https://twitter.com/InVR_Paris"
  weight = 30

[[main]]
  identifier = "instagram"
  pre = "instagram"
  url = "https://www.instagram.com/invr_paris/"
  weight = 40

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/InVR-Intech-Paris"
  weight = 50

[[footer]]
  name = "Vie privée"
  url = "#privacy"                  # * ... ToDo
