# config/_default/params.toml
#=====================================================================================================================================
# * ... DOCUMENTATION
#-------------------------------------------------------------------------------------------------------------------------------------
# CONFIGURATION         => https://nunocoracao.github.io/blowfish/docs/configuration/
# ARCHIVE               => https://web.archive.org/web/20221016143816/https://nunocoracao.github.io/blowfish/docs/configuration/
#-------------------------------------------------------------------------------------------------------------------------------------
# HOMEPAGE LAYOUT       => https://nunocoracao.github.io/blowfish/docs/homepage-layout/
# ARCHIVE               => https://web.archive.org/web/20221016144300/https://nunocoracao.github.io/blowfish/docs/homepage-layout/
#-------------------------------------------------------------------------------------------------------------------------------------
# MULTIPLE AUTHORS      => https://nunocoracao.github.io/blowfish/docs/multi-author/
# ARCHIVE               => https://web.archive.org/web/20221016155545/https://nunocoracao.github.io/blowfish/docs/multi-author/
#=====================================================================================================================================

#================
# * ... CUSTOM
#================

#-------------------
# * ... Theming
#-------------------
colorScheme                     =   "princess"      # * ... ToDo - lolilol !
defaultAppearance               =   "dark"          # * ... [OK]

#-------------------
# * ... SEO
#-------------------
robots                          =   "all"           # * ... [OK] - TeamRem: DON'T EDIT THAT OR I WILL KILL YOU (SEO).
article.showTableOfContents     =   true            # * ... [OK] - TeamRem: DON'T EDIT THAT OR I WILL KILL YOU (SEO).
article.showAuthorsBadges       =   true            # * ... [OK] - TeamRem: DON'T EDIT THAT OR I WILL KILL YOU (SEO).
article.showDateUpdated         =   true            # * ... [OK] - TeamRem: DON'T EDIT THAT OR I WILL KILL YOU (SEO Attempt).
article.showTaxonomies          =   true            # * ... [OK] - TeamRem: DON'T EDIT THAT OR I WILL KILL YOU (SEO Attempt).

#-------------------
# * ... Behaviours
#-------------------
autoSwitchAppearance            =   false           # * ... [OK] - Expected behaviour: forces the theme to be dark on First-Time Visit.
header.layout                   =   "hamburger"     # * ... [OK] - TeamRem: you can edit this as you prefer.
footer.showCopyright            =   false           # * ... [OK] - TeamRem: you can edit this as you prefer.
footer.showThemeAttribution     =   false           # * ... [OK] - TeamRem: you can edit this as you prefer.

#-------------------
# * ... Features
#-------------------
enableCodeCopy                  =   true            # * ... [OK] - TeamRem: offers a "Copy" btn on your code snippets.
enableSearch                    =   true            # * ... [OK] - TeamRem: KEEP THE THREE OUTPUTS WAYS ENABLED (HTML/RSS/JSON) OR YOU WILL INTRODUCE BREAKING CHANGES. I ALSO NEED THEM FOR HTTP REQUESTS INTERCEPTIONS & RSS SNIFFERS IN MY MONITORING TOOLS.
article.showLikes               =   true            # * ... [OK] - TeamRem: DON'T EDIT THAT OR I WILL KILL YOU (SEO Attempt).
article.showViews               =   true            # * ... [OK] - TeamRem: DON'T EDIT THAT OR I WILL KILL YOU (SEO Attempt).
article.showBreadcrumbs         =   true            # * ... [OK] - TeamRem: DON'T EDIT THAT OR I WILL KILL YOU (UX: "Fil d'ariane").
homepage.showRecent             =   true            # * ... [OK] - TeamRem: you can edit this as you prefer.

#-------------------
# * ... AREA 51
#-------------------
article.showEdit                =   false           # * ... [OK] - TeamRem: DON'T EDIT THAT OR I WILL KILL YOU (I prefer Determinism exploits/Gobuster attacks rather than crawlers with requirements set respectfully).
homepage.showMoreLinkDest       =   '/posts'        # * ... [OK] - TeamRem: DON'T EDIT THAT OR I WILL KILL YOU (BREAKING CHANGES IF THE PERMALINKS ARE NOT SET RESPECTFULLY + PROBS' WILL FUCK UP SEO FOR WEEKS IF YOU DON'T 301 ON THE HORRIBLE DOMAIN NAME REGISTRAR DASHBOARD, RESPECTFULLY TOO).

# * ... ~ End of CUSTOM ~

#================
# * ... DEFAULT
#================
# logo                          =   ""              # * ... [OK] - TeamRem: Needs to be commented out. Enable and edit this as you prefer, but TEST IT before ANY push2prod.
# mainSections                  =   ""              # * ... [OK] - TeamRem: Enable and edit this as you prefer, but TEST IT before ANY push2prod.

# article.showDate              =   true            # * ... [OK] - TeamRem: you can edit this as you prefer.
# article.showAuthor            =   true            # * ... [OK] - TeamRem: you can edit this as you prefer, but it would be very ballot to set it to false imo.
# article.showHero              =   true            # * ... [OK] - TeamRem: you can edit this as you prefer, but it would be very ballot to set it to false imo.
# article.showDraftLabel        =   true            # * ... [OK] - TeamRem: you can edit this as you prefer, but it would be very ballot to set it to false imo.
# article.editURL               =   ""              # * ... [OK] - TeamRem: DON'T EDIT THAT OR I WILL KILL YOU (I WANT TO KEEP HUGO AS A STATIC PAGE BUILDER, NOT A CMS).
# article.editAppendPath        =   true            # * ... [OK] - TeamRem: you can edit this as you prefer, but it would be very ballot to set it to false imo.
# article.showHeadingAnchors    =   true            # * ... [OK] - TeamRem: you can edit this as you prefer, but it would be very ballot to set it to false imo.
# article.showPagination        =   true            # * ... [OK] - TeamRem: you can edit this as you prefer, but it would be very ballot to set it to false imo.
# article.invertPagination      =   false           # * ... [OK] - TeamRem: you can edit this as you prefer.
# article.showReadingTime       =   true            # * ... [OK] - TeamRem: you can edit this as you prefer, but it would be very ballot to set it to false imo.
# homepage.layout               =   "page"          # * ... [OK] - TeamRem: you can edit this as you prefer, but TEST IT before ANY push2prod + Additional REM: the default behaviour is not exactly the same as the "page" state, contrary to what is documented.
# homepage.showRecentItems      =   5               # * ... [OK] - TeamRem: you can edit this as you prefer.
# homepage.showMoreLink         =   false           # * ... [OK] - TeamRem: you can edit this as you prefer, but TEST IT before ANY push2prod.

# footer.showAppearanceSwitcher =   false           # * ... [OK] - TeamRem: you can edit this as you prefer, notice this concerns the FOOTER.
# footer.showScrollToTop        =   true            # * ... [OK] - TeamRem: you can edit this as you prefer, notice this concerns the FOOTER.
